name: ecommerce_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  country_code_picker: ^2.0.2
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_verification_code: ^1.0.4
  flutter_rating_bar: ^4.0.0
  favorite_button: ^0.0.4
  carousel_slider: ^4.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/loginImg1.jpg
    - images/loginImg11.jpg
    - images/1.png
    
    - images/fashionsale.jpg
    - images/catalogue1.png
    - images/catalogue2.png
    - images/catalogue3.png
    - images/catalogue4.png
    - images/catalogue5.png
    - images/catalogue6.png
    - images/catalogue7.png
    - images/catalogue8.png

    - images/featured1.png
    - images/featured2.png
    - images/featured3.png
    - images/featured4.png

    - images/cataloguetest.jpg
    - images/cataloguetest2.jpg
    - images/olehprofile.png
    - images/favorite1.png
    - images/favorite2.png
    - images/favorite3.png
    - images/favorite4.png
    - images/favorite5.png
    - images/arrowdown.png




    - images/truck.png

    - images/creditcardicon.png
    - images/locationmarker.png

    - images/dhl.png
    - images/fedex.png
    - images/usps.png
    - images/mastercard.png
    - images/popcircle.png
    - images/successcheck.png

    - images/productimg1.jpg
    - images/productimg2.jpg
    - images/productimg3.jpg


    - images/productcolor.png
    - images/productcolor1.png
    - images/productcolor2.png
    - images/productcolor3.png
    - images/productcolor4.png
    - images/getstart.gif

    - images/iconsetting.png
    - images/iconlogout.png
    - images/iconfavorite.png
    - images/iconorder.png
    - images/iconpayment.png
    - images/iconshipping.png











    - images/cart1.png
    - images/cart2.png











  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
